
FROM python:3.9-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV APP_HOME=/app

COPY . $APP_HOME

# set working directory
WORKDIR $APP_HOME

# set environment variables

RUN pip install --upgrade pip

RUN apt-get update && apt-get install -y --no-install-recommends gcc libc-dev libpq-dev python3-dev

# install dependencies
RUN pip install -r requirements.txt && chmod +x /app/scripts/entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "/app/scripts/entrypoint.sh" ]
