
FROM python:3.9-slim


COPY . /app

# set working directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

RUN apt-get update && apt-get install -y --no-install-recommends gcc libc-dev python3-dev

RUN pip install -r requirements-dev.txt

RUN python manage.py migrate

# install dependencies
EXPOSE 8000

CMD python manage.py runserver 0.0.0.0:8000 --settings=limuwuapi.settings.base
# RUN python manage.py migrate
