version: '3.8'

services:
  limuwuapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    volumes:
      - static:./static
    depends_on:
      - postgresdb
    command: "python manage.py migrate --settings=limuwuapi.settings.prod && gunicorn limuwuapi.wsgi_prod.application --bind 0.0.0.0:8000"
  postgresdb:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env.pg
    volumes:
      - /tmp/db:/var/lib/postgresql/data
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - limuwuapi


volumes:
  static: