# Generated by Django 3.2.9 on 2021-12-07 19:40

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeAPIKey',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=40)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Free API key',
                'verbose_name_plural': 'Free API keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumAPIKey',
            fields=[
                ('prefix', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('hashed_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=40)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prem_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium API key',
                'verbose_name_plural': 'Premium API keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumAPIKeyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_tot', models.IntegerField(default=0, editable=False)),
                ('premium_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.premiumapikey')),
            ],
            bases=(core.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FreeAPIKeyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_tot', models.IntegerField(default=0, editable=False, validators=[core.models.freeapikey_max_request])),
                ('free_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.freeapikey')),
            ],
            bases=(core.models.UpdateMixin, models.Model),
        ),
    ]
